// src/utils/getSpeciesColor.js
// Returns Tailwind border color class for a species name (clean UI version)
export function getSpeciesColor(speciesName = "Unknown") {
    const speciesColors = {
        Human: "border-yellow-400",
        Droid: "border-blue-400",
        Wookie: "border-orange-400",
        Rodian: "border-green-400",
        Hutt: "border-red-400",
        "Yoda's species": "border-lime-400",
        Trandoshan: "border-emerald-400",
        "Mon Calamari": "border-cyan-400",
        Ewok: "border-amber-400",
        Sullustan: "border-sky-400",
        Neimodian: "border-teal-400",
        Gungan: "border-indigo-400",
        Toydarian: "border-rose-400",
        Dug: "border-fuchsia-400",
        "Twi'lek": "border-pink-400",
        Aleena: "border-green-300",
        Vulptereen: "border-yellow-300",
        Xexto: "border-purple-400",
        Toong: "border-orange-300",
        Cerean: "border-indigo-300",
        Nautolan: "border-teal-300",
        Zabrak: "border-red-300",
        Tholothian: "border-blue-300",
        Iktotchi: "border-sky-300",
        Quermian: "border-lime-300",
        "Kel Dor": "border-orange-300",
        Chagrian: "border-violet-300",
        Geonosian: "border-amber-300",
        Mirialan: "border-green-300",
        Clawdite: "border-yellow-300",
        Besalisk: "border-red-300",
        Kaminoan: "border-sky-300",
        Skakoan: "border-cyan-300",
        Muun: "border-rose-300",
        Togruta: "border-orange-300",
        Kaleesh: "border-amber-300",
        "Pau'an": "border-gray-300",
        Unknown: "border-gray-600",
    };

    return speciesColors[speciesName] || "border-gray-600";
}
